# Generated by Django 2.2 on 2020-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('Bussiness', 'Bussiness'), ('Individual', 'Individual')], max_length=50)),
                ('salutation', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('work_phone', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=12)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_treatment', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_supply', models.CharField(choices=[('Banglore', 'Banglore'), ('Hyderbad', 'Hyderbad')], max_length=50)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_terms', models.CharField(choices=[('Due on Receipt', 'Due on Receipt'), ('No Due on Receipt', 'No Due on Receipt')], max_length=50)),
                ('facebook', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('receivables', models.IntegerField(blank=True, null=True)),
                ('attention', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA')], max_length=50)),
                ('adress', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
